# Generated by Django 5.0.4 on 2024-04-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_created_month_post_created_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_month',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
