# Generated by Django 5.0.4 on 2024-04-29 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_created_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='.../static/assets/images/mavlonbek.jpeg', null=True, upload_to='main_img/')),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
    ]
