# Generated by Django 5.0.4 on 2024-04-29 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_month',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_year',
        ),
    ]
